### ISSUE TITLE
Can i control an existing model created ordinary by php artisan make:mode and connected to table with out making migration through this admin panel ??

### ISSUE THREAD

**Issue by alihassan161820** [zizohassan/adssystem#1]

**Comment by zizohassan** [comment]
yes you can do this 
just add table from phpmyadmin 
drage and drop the model to /app/Application/Model
change the namespace you can use this model now

**Comment by alihassan161820** [comment]
i already have a model and connected to table .. how to make it appear in admin panel to control it

**Comment by zizohassan** [comment]
الافضل انك تعمل المديول من خلال الامر
php artisan make:admin_model ModeName
عشان فيه دوال كثيرة في الكترولر و الدتا تيبل وخلافة 
بتبقي متظبته عشان تقرا من المديول اللي بيتعمل

**Comment by alihassan161820** [comment]
ما المشكلة ان هستحدم البانل علي بروجكت معمول اجزاء منه فمش هينفع ان اعمل models من الاول

**Comment by zizohassan** [comment]
بص هو ممكن بس لفة كبيرة شوية 
عشان تعمل كده فالافضل انك تاخذ الطريق الاقصر بس كده
