### ISSUE TITLE
i have this error array_combine()

### ISSUE THREAD

**Issue by enasellithy** [zizohassan/adssystem#2]
استخدم مشروعك laraflat 
قمت بانشاء المديول باستخدام امر
php artisan make:admin_model Subcategory
لما بحاول اتفرج على العنصر فى صفحه العرض بيظهر الايرور ده حاولت معه كتير لكن مفيش نتيجه وصلت ليها

ErrorException in arrays.php line 50:
array_combine(): Both parameters should have an equal number of elements (View: /home/ubuntu/workspace/laraflat/app/Application/views/admin/subcategory/show.blade.php)

**Comment by shqawe1** [comment]
اعرض ملف array.php 
وملف show.blade.php تبع Subcategory 
على شان نقدر نفيدك
