### ISSUE TITLE
how to disable sweetalert in admin panel

### ISSUE THREAD

**Issue by shqawe1** [zizohassan/adssystem#3]
Hi Dear,

I'm wondering how to disable sweetalert message in admin panel to i can catch the error because i got an error in one of my app pages but i couldn't figure out from where the error came.
Thanks in advance.

**Comment by zizohassan** [comment]
Hi shqawe1,
you go to this path 

app/Application/Controllers/Traits/ExceptionTrait.php

just comment this function

catchExceptions()

**Comment by shqawe1** [comment]
thanks a lot Eng. AbdulAziz i solve the problem by install laravel debuger package and i found the problem the form doesn't submit DATA and i'll try to solve this issue and if could i'll revert back to you.

have a nice life.

**Comment by zizohassan** [comment]
good luck
